name: Benchmarks Test

on: push

jobs:
  run-benchmarks:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: make

      - name: Run
        run: |
          - ./C-Template 1 2
          - ./C-Template 0 1 --verbose
          - ./C-Template 1 2 --quiet
          - ./C-Template 1 2 --say-hi
          - ./C-Template 1 2 --say-hi=CI
          - ./C-Template 1 2 --say-hi=CI --fail-on-match 42
